# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MakeEstimable <- function(v) {
    invisible(.Call(`_ADinR_MakeEstimable`, v))
}

Variable <- function() {
    .Call(`_ADinR_Variable`)
}

Parameter <- function() {
    .Call(`_ADinR_Parameter`)
}

GetValues <- function() {
    .Call(`_ADinR_GetValues`)
}

Show <- function(v) {
    invisible(.Call(`_ADinR_Show`, v))
}

Gradient <- function(x) {
    .Call(`_ADinR_Gradient`, x)
}

Clear <- function() {
    invisible(.Call(`_ADinR_Clear`))
}

SetRecording <- function(record) {
    invisible(.Call(`_ADinR_SetRecording`, record))
}

Minimize <- function(control = NULL) {
    .Call(`_ADinR_Minimize`, control)
}

ACos <- function(x) {
    .Call(`_ADinR_ACos`, x)
}

ASin <- function(x) {
    .Call(`_ADinR_ASin`, x)
}

ATan <- function(x) {
    .Call(`_ADinR_ATan`, x)
}

Cos <- function(x) {
    .Call(`_ADinR_Cos`, x)
}

Cosh <- function(x) {
    .Call(`_ADinR_Cosh`, x)
}

Sin <- function(x) {
    .Call(`_ADinR_Sin`, x)
}

Sinh <- function(x) {
    .Call(`_ADinR_Sinh`, x)
}

Tan <- function(x) {
    .Call(`_ADinR_Tan`, x)
}

Tanh <- function(x) {
    .Call(`_ADinR_Tanh`, x)
}

Exp <- function(x) {
    .Call(`_ADinR_Exp`, x)
}

Log <- function(x) {
    .Call(`_ADinR_Log`, x)
}

Log10 <- function(x) {
    .Call(`_ADinR_Log10`, x)
}

Pow <- function(a, b) {
    .Call(`_ADinR_Pow`, a, b)
}

Add <- function(a, b) {
    .Call(`_ADinR_Add`, a, b)
}

Sub <- function(a, b) {
    .Call(`_ADinR_Sub`, a, b)
}

Mult <- function(a, b) {
    .Call(`_ADinR_Mult`, a, b)
}

Div <- function(a, b) {
    .Call(`_ADinR_Div`, a, b)
}

